In [1]:
print ('hello world')

hello world

In [11]:
# leer un archivo .csv
import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [14]:
import pandas as pd
path = 'datos.xls'
df = pd.read_excel(path)
print(df)
# imprime solo la primera hoja del archivo .xls

  ID GRD      Nombre GRD  Costo resolución en Clínica Privada [MM$]
0   GRD1       Coronario                                      7.917
1   GRD2        Hepático                                      3.417
2   GRD3    Respiratorio                                      2.915
3   GRD4           Renal                                      6.188
4   GRD5     Neurológico                                      6.782
5   GRD6  Traumatológico                                      4.881
6   GRD7       Esofágico                                      2.629
7   GRD8   Oftalmológico                                      6.720
8   GRD9    Circulatorio                                      5.524
9  GRD10      Intestinal                                      7.916

In [1]:
import pandas as pd

# Leer un archivo .xlsx con varias hojas
xlsx = pd.read_excel('datos.xls', sheet_name=None)

# Imprimir el nombre de cada hoja y su contenido
for hoja, datos in xlsx.items():
    print("Nombre de la hoja:", hoja)
    print(datos)
    print()

Nombre de la hoja: GRD
  ID GRD      Nombre GRD  Costo resolución en Clínica Privada [MM$]
0   GRD1       Coronario                                      7.917
1   GRD2        Hepático                                      3.417
2   GRD3    Respiratorio                                      2.915
3   GRD4           Renal                                      6.188
4   GRD5     Neurológico                                      6.782
5   GRD6  Traumatológico                                      4.881
6   GRD7       Esofágico                                      2.629
7   GRD8   Oftalmológico                                      6.720
8   GRD9    Circulatorio                                      5.524
9  GRD10      Intestinal                                      7.916

Nombre de la hoja: Hospitales
                             Nombre Servicio de Salud  \
0   Metropolitano Norte                           ...
1   Metropolitano Occidente                       ...
2   Metropolitano Occidente                       ...
3   Metropolitano Occidente                       ...
4   Metropolitano Occidente                       ...
5   Metropolitano Central                         ...
6   Metropolitano Central                         ...
7   Metropolitano Central                         ...
8   Metropolitano Oriente                         ...
9   Metropolitano Oriente                         ...
10  Metropolitano Oriente                         ...
11  Metropolitano Oriente                         ...
12  Metropolitano Sur                             ...
13  Metropolitano Sur                             ...
14  Metropolitano Sur                             ...
15  Metropolitano Sur                             ...
16  Metropolitano Sur                             ...
17  Metropolitano Sur Oriente                     ...
18  Metropolitano Sur Oriente                     ...
19  Metropolitano Sur Oriente                     ...
20  Metropolitano Sur Oriente                     ...

                               Nombre Establecimiento  \
0                      Complejo Hospitalario San José
1              Hospital Adalberto Steeger (Talagante)
2                     Hospital Dr. Félix Bulnes Cerda
3                           Hospital San Juan de Dios
4        Instituto Traumatológico Dr. Teodoro Gebauer
5                 Hospital Clínico San Borja-Arriarán
6   Hospital de Urgencia Asistencia Pública Dr. Al...
7                                  Hospital el Carmen
8                               Hospital Del Salvador
9                          Hospital Dr. Luis Tisné B.
10       Instituto de Neurocirugía Dr. Alfonso Asenjo
11  Instituto Nacional de Enfermedades Respiratori...
12                       Hospital Barros Luco Trudeau
13  Hospital de Enfermedades Infecciosas Dr. Lucio...
14              Hospital Dr. Exequiel González Cortés
15                                   Hospital El Pino
16          Hospital Parroquial de San Bernardo
17         Complejo Hospitalario Dr. Sótero del Río
18                     Hospital Clínico de la Florida
19              Hospital Metropolitano ( ex Militar )
20         Hospital Padre Alberto Hurtado (San Ramón)

    Área Cuidados Intensivos Adultos  Área Cuidados Intermedios Adulto  \
0                                 11                                33
1                                  6                                11
2                                  3                                 6
3                                 29                                47
4                                 12                                 6
5                                 17                                26
6                                 24                                20
7                                  6                                12
8                                 22                                24
9                                  8                                16
10                                12                                11
11                                15                                29
12                                31                                43
13                                11                                 9
14                                23                                 8
15                                12                                20
16                                 6                                10
17                                20                                35
18                                 9                                15
19                                12                                20
20                                 6                                10

    Total Camas Críticas  Máxima cantidad de camas a aumetar  \
0                     44                                  10
1                     17                                   5
2                      9                                   5
3                     76                                  30
4                     18                                   5
5                     43                                  10
6                     44                                  10
7                     18                                   4
8                     46                                  12
9                     24                                   8
10                    23                                   8
11                    44                                  15
12                    74                                  25
13                    20                                   5
14                    31                                   5
15                    32                                   9
16                    16                                   4
17                    55                                  12
18                    24                                   5
19                    32                                   5
20                    16                                   5

    Costo de instalar una cama [MM$]  \
0                               1407
1                               1263
2                               1310
3                               1066
4                               1433
5                               1347
6                               1256
7                               1368
8                               1075
9                               1056
10                              1256
11                              1422
12                              1319
13                              1193
14                              1304
15                              1074
16                              1051
17                              1203
18                              1028
19                              1093
20                              1166

    Costo de operación anual de una cama [MM$]  Costo diario GRD1 [MM$]  \
0                                         47.2                    0.593
1                                         62.1                    0.493
2                                         65.9                    0.580
3                                         39.2                    0.482
4                                         55.5                    0.407
5                                         63.1                    0.509
6                                         44.5                    0.468
7                                         49.7                    0.444
8                                         45.4                    0.444
9                                         56.2                    0.386
10                                        36.6                    0.376
11                                        63.0                    0.498
12                                        42.9                    0.551
13                                        61.6                    0.540
14                                        51.9                    0.398
15                                        66.1                    0.546
16                                        47.0                    0.541
17                                        40.6                    0.560
18                                        60.0                    0.527
19                                        46.3                    0.549
20                                        43.2                    0.479

    Costo diario GRD2 [MM$]  Costo diario GRD3 [MM$]  Costo diario GRD4 [MM$]  \
0                     0.509                    0.367                    0.492
1                     0.357                    0.429                    0.382
2                     0.325                    0.375                    0.409
3                     0.554                    0.564                    0.331
4                     0.449                    0.468                    0.433
5                     0.363                    0.575                    0.534
6                     0.509                    0.343                    0.391
7                     0.439                    0.386                    0.569
8                     0.339                    0.345                    0.544
9                     0.477                    0.491                    0.312
10                    0.481                    0.476                    0.407
11                    0.465                    0.482                    0.512
12                    0.339                    0.587                    0.416
13                    0.407                    0.590                    0.492
14                    0.343                    0.454                    0.493
15                    0.599                    0.550                    0.383
16                    0.546                    0.533                    0.411
17                    0.388                    0.584                    0.458
18                    0.552                    0.431                    0.594
19                    0.553                    0.471                    0.346
20                    0.579                    0.387                    0.509

    Costo diario GRD5 [MM$]  Costo diario GRD6 [MM$]  Costo diario GRD7 [MM$]  \
0                     0.524                    0.405                    0.571
1                     0.469                    0.386                    0.543
2                     0.561                    0.362                    0.328
3                     0.438                    0.509                    0.544
4                     0.573                    0.392                    0.409
5                     0.367                    0.567                    0.576
6                     0.390                    0.404                    0.457
7                     0.404                    0.416                    0.302
8                     0.458                    0.531                    0.340
9                     0.452                    0.362                    0.435
10                    0.573                    0.302                    0.535
11                    0.597                    0.390                    0.302
12                    0.545                    0.306                    0.347
13                    0.458                    0.361                    0.420
14                    0.489                    0.444                    0.323
15                    0.569                    0.442                    0.543
16                    0.534                    0.466                    0.313
17                    0.451                    0.595                    0.336
18                    0.331                    0.341                    0.580
19                    0.582                    0.331                    0.456
20                    0.571                    0.516                    0.584

    Costo diario GRD8 [MM$]  Costo diario GRD9 [MM$]  Costo diario GRD10 [MM$]
0                     0.474                    0.498                     0.305
1                     0.362                    0.564                     0.333
2                     0.314                    0.536                     0.436
3                     0.410                    0.441                     0.359
4                     0.391                    0.418                     0.334
5                     0.482                    0.320                     0.574
6                     0.411                    0.330                     0.568
7                     0.414                    0.494                     0.425
8                     0.491                    0.377                     0.443
9                     0.305                    0.482                     0.421
10                    0.520                    0.407                     0.420
11                    0.566                    0.428                     0.439
12                    0.548                    0.501                     0.419
13                    0.452                    0.331                     0.330
14                    0.572                    0.500                     0.310
15                    0.504                    0.590                     0.549
16                    0.500                    0.523                     0.310
17                    0.525                    0.472                     0.403
18                    0.528                    0.537                     0.505
19                    0.394                    0.410                     0.563
20                    0.382                    0.462                     0.424

Nombre de la hoja: Información Histórica
       Número de llegada                              Hospital al que llega  \
0                      1       Instituto Traumatológico Dr. Teodoro Gebauer
1                      2                Hospital Clínico San Borja-Arriarán
2                      3                         Hospital Dr. Luis Tisné B.
3                      4              Hospital Dr. Exequiel González Cortés
4                      5                       Hospital Barros Luco Trudeau
...                  ...                                                ...
65529              65530                Hospital Clínico San Borja-Arriarán
65530              65531              Hospital Dr. Exequiel González Cortés
65531              65532                              Hospital Del Salvador
65532              65533  Hospital de Enfermedades Infecciosas Dr. Lucio...
65533              65534  Hospital de Urgencia Asistencia Pública Dr. Al...

         GRD  Día de llegada  Día de salida  Estadia
0       GRD3               1              4        3
1       GRD7               1              5        4
2       GRD7               1              5        4
3      GRD10               1             11       10
4       GRD6               1              6        5
...      ...             ...            ...      ...
65529   GRD2             424            428        4
65530   GRD9             424            429        5
65531  GRD10             424            434       10
65532   GRD3             424            427        3
65533   GRD7             424            428        4

[65534 rows x 6 columns]

Nombre de la hoja: Clase 1
   Dia  Llegada
0    1        4
1    2        5
2    3        5
3    4        2
4    5        4
5    6        5
6    7        6
7    8        5
8    9        5
9   10        5

In [ ]:
import pandas as pd

# Leer un archivo .xlsx y leer una hoja en específico 
xlsx = pd.read_excel('datos.xls', sheet_name='Hospitales')

# Imprimir el nombre de la hoja y su contenido
for x, datos in xlsx.items():
    print(x)
    print(datos)
    print()

Nombre Servicio de Salud
0     Metropolitano Norte                           ...
1     Metropolitano Occidente                       ...
2     Metropolitano Occidente                       ...
3     Metropolitano Occidente                       ...
4     Metropolitano Occidente                       ...
5     Metropolitano Central                         ...
6     Metropolitano Central                         ...
7     Metropolitano Central                         ...
8     Metropolitano Oriente                         ...
9     Metropolitano Oriente                         ...
10    Metropolitano Oriente                         ...
11    Metropolitano Oriente                         ...
12    Metropolitano Sur                             ...
13    Metropolitano Sur                             ...
14    Metropolitano Sur                             ...
15    Metropolitano Sur                             ...
16    Metropolitano Sur                             ...
17    Metropolitano Sur Oriente                     ...
18    Metropolitano Sur Oriente                     ...
19    Metropolitano Sur Oriente                     ...
20    Metropolitano Sur Oriente                     ...
Name: Nombre Servicio de Salud, dtype: object

Nombre Establecimiento
0                        Complejo Hospitalario San José
1                Hospital Adalberto Steeger (Talagante)
2                       Hospital Dr. Félix Bulnes Cerda
3                             Hospital San Juan de Dios
4          Instituto Traumatológico Dr. Teodoro Gebauer
5                   Hospital Clínico San Borja-Arriarán
6     Hospital de Urgencia Asistencia Pública Dr. Al...
7                                    Hospital el Carmen
8                                 Hospital Del Salvador
9                            Hospital Dr. Luis Tisné B.
10         Instituto de Neurocirugía Dr. Alfonso Asenjo
11    Instituto Nacional de Enfermedades Respiratori...
12                         Hospital Barros Luco Trudeau
13    Hospital de Enfermedades Infecciosas Dr. Lucio...
14                Hospital Dr. Exequiel González Cortés
15                                     Hospital El Pino
16            Hospital Parroquial de San Bernardo
17           Complejo Hospitalario Dr. Sótero del Río
18                       Hospital Clínico de la Florida
19                Hospital Metropolitano ( ex Militar )
20           Hospital Padre Alberto Hurtado (San Ramón)
Name: Nombre Establecimiento, dtype: object

Área Cuidados Intensivos Adultos
0     11
1      6
2      3
3     29
4     12
5     17
6     24
7      6
8     22
9      8
10    12
11    15
12    31
13    11
14    23
15    12
16     6
17    20
18     9
19    12
20     6
Name: Área Cuidados Intensivos Adultos, dtype: int64

Área Cuidados Intermedios Adulto
0     33
1     11
2      6
3     47
4      6
5     26
6     20
7     12
8     24
9     16
10    11
11    29
12    43
13     9
14     8
15    20
16    10
17    35
18    15
19    20
20    10
Name: Área Cuidados Intermedios Adulto, dtype: int64

Total Camas Críticas
0     44
1     17
2      9
3     76
4     18
5     43
6     44
7     18
8     46
9     24
10    23
11    44
12    74
13    20
14    31
15    32
16    16
17    55
18    24
19    32
20    16
Name: Total Camas Críticas, dtype: int64

Máxima cantidad de camas a aumetar
0     10
1      5
2      5
3     30
4      5
5     10
6     10
7      4
8     12
9      8
10     8
11    15
12    25
13     5
14     5
15     9
16     4
17    12
18     5
19     5
20     5
Name: Máxima cantidad de camas a aumetar, dtype: int64

Costo de instalar una cama [MM$]
0     1407
1     1263
2     1310
3     1066
4     1433
5     1347
6     1256
7     1368
8     1075
9     1056
10    1256
11    1422
12    1319
13    1193
14    1304
15    1074
16    1051
17    1203
18    1028
19    1093
20    1166
Name: Costo de instalar una cama [MM$], dtype: int64

Costo de operación anual de una cama [MM$]
0     47.2
1     62.1
2     65.9
3     39.2
4     55.5
5     63.1
6     44.5
7     49.7
8     45.4
9     56.2
10    36.6
11    63.0
12    42.9
13    61.6
14    51.9
15    66.1
16    47.0
17    40.6
18    60.0
19    46.3
20    43.2
Name: Costo de operación anual de una cama [MM$], dtype: float64

Costo diario GRD1 [MM$]
0     0.593
1     0.493
2     0.580
3     0.482
4     0.407
5     0.509
6     0.468
7     0.444
8     0.444
9     0.386
10    0.376
11    0.498
12    0.551
13    0.540
14    0.398
15    0.546
16    0.541
17    0.560
18    0.527
19    0.549
20    0.479
Name: Costo diario GRD1 [MM$], dtype: float64

Costo diario GRD2 [MM$]
0     0.509
1     0.357
2     0.325
3     0.554
4     0.449
5     0.363
6     0.509
7     0.439
8     0.339
9     0.477
10    0.481
11    0.465
12    0.339
13    0.407
14    0.343
15    0.599
16    0.546
17    0.388
18    0.552
19    0.553
20    0.579
Name: Costo diario GRD2 [MM$], dtype: float64

Costo diario GRD3 [MM$]
0     0.367
1     0.429
2     0.375
3     0.564
4     0.468
5     0.575
6     0.343
7     0.386
8     0.345
9     0.491
10    0.476
11    0.482
12    0.587
13    0.590
14    0.454
15    0.550
16    0.533
17    0.584
18    0.431
19    0.471
20    0.387
Name: Costo diario GRD3 [MM$], dtype: float64

Costo diario GRD4 [MM$]
0     0.492
1     0.382
2     0.409
3     0.331
4     0.433
5     0.534
6     0.391
7     0.569
8     0.544
9     0.312
10    0.407
11    0.512
12    0.416
13    0.492
14    0.493
15    0.383
16    0.411
17    0.458
18    0.594
19    0.346
20    0.509
Name: Costo diario GRD4 [MM$], dtype: float64

Costo diario GRD5 [MM$]
0     0.524
1     0.469
2     0.561
3     0.438
4     0.573
5     0.367
6     0.390
7     0.404
8     0.458
9     0.452
10    0.573
11    0.597
12    0.545
13    0.458
14    0.489
15    0.569
16    0.534
17    0.451
18    0.331
19    0.582
20    0.571
Name: Costo diario GRD5 [MM$], dtype: float64

Costo diario GRD6 [MM$]
0     0.405
1     0.386
2     0.362
3     0.509
4     0.392
5     0.567
6     0.404
7     0.416
8     0.531
9     0.362
10    0.302
11    0.390
12    0.306
13    0.361
14    0.444
15    0.442
16    0.466
17    0.595
18    0.341
19    0.331
20    0.516
Name: Costo diario GRD6 [MM$], dtype: float64

Costo diario GRD7 [MM$]
0     0.571
1     0.543
2     0.328
3     0.544
4     0.409
5     0.576
6     0.457
7     0.302
8     0.340
9     0.435
10    0.535
11    0.302
12    0.347
13    0.420
14    0.323
15    0.543
16    0.313
17    0.336
18    0.580
19    0.456
20    0.584
Name: Costo diario GRD7 [MM$], dtype: float64

Costo diario GRD8 [MM$]
0     0.474
1     0.362
2     0.314
3     0.410
4     0.391
5     0.482
6     0.411
7     0.414
8     0.491
9     0.305
10    0.520
11    0.566
12    0.548
13    0.452
14    0.572
15    0.504
16    0.500
17    0.525
18    0.528
19    0.394
20    0.382
Name: Costo diario GRD8 [MM$], dtype: float64

Costo diario GRD9 [MM$]
0     0.498
1     0.564
2     0.536
3     0.441
4     0.418
5     0.320
6     0.330
7     0.494
8     0.377
9     0.482
10    0.407
11    0.428
12    0.501
13    0.331
14    0.500
15    0.590
16    0.523
17    0.472
18    0.537
19    0.410
20    0.462
Name: Costo diario GRD9 [MM$], dtype: float64

Costo diario GRD10 [MM$]
0     0.305
1     0.333
2     0.436
3     0.359
4     0.334
5     0.574
6     0.568
7     0.425
8     0.443
9     0.421
10    0.420
11    0.439
12    0.419
13    0.330
14    0.310
15    0.549
16    0.310
17    0.403
18    0.505
19    0.563
20    0.424
Name: Costo diario GRD10 [MM$], dtype: float64

In [4]:
#código que permite calcular el total de camas críticas para cada uno de los servicios de salud

import pandas as pd

# Leer dos columnas específicas de una hoja de un archivo de Excel y el titulo de las columnas necesarias
df = pd.read_excel('datos.xls', sheet_name='Hospitales', usecols=['Nombre Servicio de Salud','Total Camas Críticas'])

suma = df.groupby('Nombre Servicio de Salud').sum()  
# Imprimir el total de camas críticas por servicio
print(suma)
print()
minimo = df.groupby('Nombre Servicio de Salud').min()
# Imprimir el minimo de camas críticas por servicio
print(minimo)
print()
# Imprimir servicios de salud son los tres servicios que tienen más camas críticas 
tresServiciosConMasCamasCriticas = suma['Total Camas Críticas'].nlargest(3)
print(tresServiciosConMasCamasCriticas)

                                                    Total Camas Críticas
Nombre Servicio de Salud
Metropolitano Central                                                105
Metropolitano Norte                                                   44
Metropolitano Occidente                                              120
Metropolitano Oriente                                                137
Metropolitano Sur                                                    173
Metropolitano Sur Oriente                                            127

                                                    Total Camas Críticas
Nombre Servicio de Salud
Metropolitano Central                                                 18
Metropolitano Norte                                                   44
Metropolitano Occidente                                                9
Metropolitano Oriente                                                 23
Metropolitano Sur                                                     16
Metropolitano Sur Oriente                                             16

Nombre Servicio de Salud
Metropolitano Sur                                     173
Metropolitano Oriente                                 137
Metropolitano Sur Oriente                             127
Name: Total Camas Críticas, dtype: int64

In [5]:
# #código que permite calcular el total de camas críticas para cada uno de los servicios de salud
import pandas as pd
# Leer dos columnas específicas de una hoja de un archivo de Excel
df = pd.read_excel('datos.xls', sheet_name='Hospitales')
suma = df[['Nombre Servicio de Salud','Total Camas Críticas']].groupby('Nombre Servicio de Salud').sum()  
# Imprimir el resultado
print(suma)

                                                    Total Camas Críticas
Nombre Servicio de Salud
Metropolitano Central                                                105
Metropolitano Norte                                                   44
Metropolitano Occidente                                              120
Metropolitano Oriente                                                137
Metropolitano Sur                                                    173
Metropolitano Sur Oriente                                            127

In [6]:
import pandas as pd

# Crear un ejemplo de DataFrame
df = pd.DataFrame({'col1': [1, 2, 3, 4, 5, 6]})

# Obtener los tres valores máximos
result = df['col1'].nlargest(3)

# Imprimir el resultado
print(result)

5    6
4    5
3    4
Name: col1, dtype: int64

In [ ]:
# Códigos que permite calcular el costo promedio diario de atención para el GRD4
import pandas as pd

# Crear un ejemplo de DataFrame
df = pd.read_excel('datos.xls', sheet_name='Hospitales')

# Calcular el promedio de los valores en la columna 'Costo diario GRD4 [MM$]'
mean = df['Costo diario GRD4 [MM$]'].mean()

# Imprimir el resultado
print(mean)

0.4484761904761904

In [7]:
import pandas as pd

# Crear un ejemplo de DataFrame
df = pd.DataFrame({'col1': [1, 2, 3, 4, 5, 6]})

# Seleccionar las filas desde la tercera hasta la quinta (incluyendo ambos extremos)
selected_rows = df[2:5]

# Seleccionar la columna 'col1' de las filas seleccionadas
selected_col = selected_rows['col1']

# Imprimir el resultado
print(selected_col)

2    3
3    4
4    5
Name: col1, dtype: int64

In [46]:
# ¿Cuál cifra corresponde al promedio diario de pacientes que han llegado a la red en los últimos 10 días (desde el día 415 al día 424)? 
import pandas as pd
df = pd.read_excel('datos.xls', sheet_name='Información Histórica')
df_rango = df.loc[(df['Día de llegada'] >= 415)]
conteo = df_rango['Día de llegada'].value_counts()
print(conteo)
print()
print(conteo.mean())

420    183
417    170
418    167
422    160
419    159
421    159
423    159
416    157
415    149
424     82
Name: Día de llegada, dtype: int64

154.5
183

In [45]:
# ¿Cuál es el promedio del costo diario de resolución en clínica privada de los 3 GRDs más costos?
import pandas as pd
df= pd.read_excel('datos.xls', sheet_name='GRD')
sorted_df = df.sort_values('Costo resolución en Clínica Privada [MM$]', ascending=False)
top_three = sorted_df.iloc[:3]['Costo resolución en Clínica Privada [MM$]']
promedio = top_three.mean()
print(promedio)

7.538333333333334

In [43]:
# ¿Qué cifra corresponde a la diferencia entre el menor y mayor costo, de operación anual de una cama para cada servicio de salud?
import pandas as pd
df= pd.read_excel('datos.xls', sheet_name='Hospitales')
max = df['Costo de operación anual de una cama [MM$]'].max() 
min = df['Costo de operación anual de una cama [MM$]'].min() 
dif = max - min
print(dif)

29.499999999999993

In [58]:
# ¿Cuántos pacientes llegaron a la red el día que llegaron más pacientes? 
import pandas as pd
df= pd.read_excel('datos.xls', sheet_name='Información Histórica')
# df_rango = df.loc[(df['Día de llegada'] >= 1)]
# conteo = df_rango['Día de llegada'].value_counts()
conteo = df['Día de llegada'].value_counts()
print(conteo)
print()
print(conteo.max())

420    183
403    182
216    175
262    174
223    174
      ...
116    136
134    136
58     132
50     130
424     82
Name: Día de llegada, Length: 424, dtype: int64

183

In [60]:
# Este código permite determinar el promedio del total de camas críticas para cada servicio de la red 
import pandas as pd
df= pd.read_excel('datos.xls', sheet_name='Hospitales')
df[["Nombre Servicio de Salud", "Total Camas Críticas"]].groupby("Nombre Servicio de Salud").mean()

                                                    Total Camas Críticas
Nombre Servicio de Salud
Metropolitano Central                                              35.00
Metropolitano Norte                                                44.00
Metropolitano Occidente                                            30.00
Metropolitano Oriente                                              34.25
Metropolitano Sur                                                  34.60
Metropolitano Sur Oriente                                          31.75

In [64]:
# Este código permite determinar el valor del costo para instalar 3 camas nuevas y de las menos costosas- en cada servicio de salud
import pandas as pd
df= pd.read_excel('datos.xls', sheet_name='Hospitales')
costo_camas = df[["Nombre Servicio de Salud", "Costo de instalar una cama [MM$]"]].groupby("Nombre Servicio de Salud").min()
print(costo_camas)
print()
costo_camas["Costo 3 camas nuevas"] = costo_camas["Costo de instalar una cama [MM$]"]*3
print(costo_camas)

                                                    Costo de instalar una cama [MM$]
Nombre Servicio de Salud
Metropolitano Central                                                           1256
Metropolitano Norte                                                             1407
Metropolitano Occidente                                                         1066
Metropolitano Oriente                                                           1056
Metropolitano Sur                                                               1051
Metropolitano Sur Oriente                                                       1028

                                                    Costo de instalar una cama [MM$]  \
Nombre Servicio de Salud
Metropolitano Central                                                           1256
Metropolitano Norte                                                             1407
Metropolitano Occidente                                                         1066
Metropolitano Oriente                                                           1056
Metropolitano Sur                                                               1051
Metropolitano Sur Oriente                                                       1028

                                                    Costo 3 camas nuevas
Nombre Servicio de Salud
Metropolitano Central                                               3768
Metropolitano Norte                                                 4221
Metropolitano Occidente                                             3198
Metropolitano Oriente                                               3168
Metropolitano Sur                                                   3153
Metropolitano Sur Oriente                                           3084

In [14]:
# Ejemplo Series basado en Tabla GRD
import pandas as pd
# Datos
d={'GRD1':"Coronario", 'GRD2':"Hepático", 'GRD3': "Respiratorio"}
# Comando Pandas.Series(datos, indice de datos)
ser = pd.Series(data=d, index=['GRD1','GRD2','GRD3'])
# Despliega series
ser

GRD1       Coronario
GRD2        Hepático
GRD3    Respiratorio
dtype: object

In [13]:
# DataFrame
import pandas as pd
data = {'ID GRD':['GRD1','GRD2','GRD3','GRD4','GRD5','GRD6','GRD7','GRD8','GRD9','GRD10'],
        'Nombre GRD':['Coronario','Hepático','Respiratorio','Renal','Neuro','Trauma','Esofágico','Oftalmológico','Circulatorio','Intestinal'],
        'Costo [MM$]':[7.92,3.42,2.92,6.19,6.78,4.88,2.63,6.72,5.5,7.92]}
df=pd.DataFrame(data=data)
df

  ID GRD     Nombre GRD  Costo [MM$]
0   GRD1      Coronario         7.92
1   GRD2       Hepático         3.42
2   GRD3   Respiratorio         2.92
3   GRD4          Renal         6.19
4   GRD5          Neuro         6.78
5   GRD6         Trauma         4.88
6   GRD7      Esofágico         2.63
7   GRD8  Oftalmológico         6.72
8   GRD9   Circulatorio         5.50
9  GRD10     Intestinal         7.92

In [25]:
# Leer archivo excel
import pandas as pd
GRD_sheet=pd.read_excel('Datos.xls', sheet_name='GRD', header=0, index_col=None)
# Número de filas empezando de arriba (3)
print(GRD_sheet.head(3))
print()
# Número de filas empezando de abajo (4)
print(GRD_sheet.tail(4))

  ID GRD    Nombre GRD  Costo resolución en Clínica Privada [MM$]
0   GRD1     Coronario                                      7.917
1   GRD2      Hepático                                      3.417
2   GRD3  Respiratorio                                      2.915

  ID GRD     Nombre GRD  Costo resolución en Clínica Privada [MM$]
6   GRD7      Esofágico                                      2.629
7   GRD8  Oftalmológico                                      6.720
8   GRD9   Circulatorio                                      5.524
9  GRD10     Intestinal                                      7.916

In [26]:
import pandas as pd
Hosp_sheet=pd.read_excel('Datos.xls', sheet_name='Hospitales', header=0, index_col=None)
Hosp_sheet.head()

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
0,Metropolitano Norte ...,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305
1,Metropolitano Occidente ...,Hospital Adalberto Steeger (Talagante),6,11,17,5,1263,62.1,0.493,0.357,0.429,0.382,0.469,0.386,0.543,0.362,0.564,0.333
2,Metropolitano Occidente ...,Hospital Dr. Félix Bulnes Cerda,3,6,9,5,1310,65.9,0.580,0.325,0.375,0.409,0.561,0.362,0.328,0.314,0.536,0.436
3,Metropolitano Occidente ...,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359
4,Metropolitano Occidente ...,Instituto Traumatológico Dr. Teodoro Gebauer,12,6,18,5,1433,55.5,0.407,0.449,0.468,0.433,0.573,0.392,0.409,0.391,0.418,0.334

In [66]:
# ¿Cuál de las siguientes alternativas indica correctamente el promedio de camas de cuidados intensivos adultos existentes en el Servicio de Salud Metropolitano?.
import pandas as pd
Hosp_sheet=pd.read_excel('Datos.xls', sheet_name='Hospitales', header=0, index_col=None)
# Promedio de camas de cuidados intensivos adultos por servicio de salud.
print(Hosp_sheet[['Nombre Servicio de Salud','Área Cuidados Intensivos Adultos']].groupby('Nombre Servicio de Salud').mean())
print()
# Promedio de camas de cuidados intensivos adultos existentes en el Servicio de Salud Metropolitano.
print(Hosp_sheet['Área Cuidados Intensivos Adultos'].mean())
print()
# Promedio histórico estadía por GRD.
Info_sheet=pd.read_excel('Datos.xls', sheet_name='Información Histórica', header=0, index_col=None)
print(Info_sheet[['GRD','Estadia']].groupby('GRD').mean())

                                                    Área Cuidados Intensivos Adultos
Nombre Servicio de Salud
Metropolitano Central                                                      15.666667
Metropolitano Norte                                                        11.000000
Metropolitano Occidente                                                    12.500000
Metropolitano Oriente                                                      14.250000
Metropolitano Sur                                                          16.600000
Metropolitano Sur Oriente                                                  11.750000

14.047619047619047

       Estadia
GRD
GRD1      10.0
GRD10     10.0
GRD2       4.0
GRD3       3.0
GRD4       6.0
GRD5       4.0
GRD6       5.0
GRD7       4.0
GRD8       4.0
GRD9       5.0

In [65]:
# Promedio Costo resolución en Clínica Privada [MM$].
import pandas as pd
GRD_sheet=pd.read_excel('Datos.xls', sheet_name='GRD', header=0, index_col=None)
GRD_sheet['Costo resolución en Clínica Privada [MM$]'].mean()

5.488899999999999

In [40]:
# Ordenar de mayor a menor valores de Costo resolución en Clínica Privada [MM$].
import pandas as pd
GRD_sheet=pd.read_excel('Datos.xls', sheet_name='GRD', header=0, index_col=None)
GRD_sheet.sort_values(by=['Costo resolución en Clínica Privada [MM$]'], ascending=False)
# Si ascending = True va de menor a mayor

  ID GRD      Nombre GRD  Costo resolución en Clínica Privada [MM$]
0   GRD1       Coronario                                      7.917
9  GRD10      Intestinal                                      7.916
4   GRD5     Neurológico                                      6.782
7   GRD8   Oftalmológico                                      6.720
3   GRD4           Renal                                      6.188
8   GRD9    Circulatorio                                      5.524
5   GRD6  Traumatológico                                      4.881
1   GRD2        Hepático                                      3.417
2   GRD3    Respiratorio                                      2.915
6   GRD7       Esofágico                                      2.629

In [58]:
# ¿Cuál de las siguientes alternativas indica correctamente el costo máximo diario de atención en el Servicio de Salud Metropolitano?
import pandas as pd
Hosp_sheet=pd.read_excel('Datos.xls', sheet_name='Hospitales', header=0, index_col=None)
print(Hosp_sheet[['Costo diario GRD1 [MM$]','Costo diario GRD2 [MM$]','Costo diario GRD3 [MM$]','Costo diario GRD4 [MM$]','Costo diario GRD5 [MM$]',
            'Costo diario GRD6 [MM$]','Costo diario GRD7 [MM$]','Costo diario GRD8 [MM$]','Costo diario GRD9 [MM$]','Costo diario GRD10 [MM$]']].max().max())
print()
print(Hosp_sheet.max())
print()

0.599

Nombre Servicio de Salud                      Metropolitano Sur Oriente                     ...
Nombre Establecimiento                             Instituto de Neurocirugía Dr. Alfonso Asenjo
Área Cuidados Intensivos Adultos                                                             31
Área Cuidados Intermedios Adulto                                                             47
Total Camas Críticas                                                                         76
Máxima cantidad de camas a aumetar                                                           30
Costo de instalar una cama [MM$]                                                           1433
Costo de operación anual de una cama [MM$]                                                 66.1
Costo diario GRD1 [MM$]                                                                   0.593
Costo diario GRD2 [MM$]                                                                   0.599
Costo diario GRD3 [MM$]                                                                    0.59
Costo diario GRD4 [MM$]                                                                   0.594
Costo diario GRD5 [MM$]                                                                   0.597
Costo diario GRD6 [MM$]                                                                   0.595
Costo diario GRD7 [MM$]                                                                   0.584
Costo diario GRD8 [MM$]                                                                   0.572
Costo diario GRD9 [MM$]                                                                    0.59
Costo diario GRD10 [MM$]                                                                  0.574
dtype: object

In [63]:
# Obtener valor maximo y valor minimo de la columna de costos
import pandas as pd
GRD_sheet=pd.read_excel('Datos.xls', sheet_name='GRD', header=0, index_col=None)
print(GRD_sheet['Costo resolución en Clínica Privada [MM$]'].max())
print(GRD_sheet['Costo resolución en Clínica Privada [MM$]'].min())

7.917
2.629